# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
generate_missing_sql_type_definitions = true
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "C:\\projects\\MahjongAtHome\\mahjong-at-home-api\\migrations"
