//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_info")]
pub struct Model {
    #[sea_orm(unique, primary_key, auto_increment = false)]
    pub user_id: i32,
    pub nickname: String,
    pub declaration: String,
    pub age: i16,
    pub gender: i16,
    pub mbti_ei: i16,
    pub mbti_ns: i16,
    pub mbti_ft: i16,
    pub mbti_jp: i16,
    pub speed: i16,
    pub speek: i16,
    pub score: i16,
    pub location: String,
    #[sea_orm(column_type = "Double")]
    pub lon: f64,
    #[sea_orm(column_type = "Double")]
    pub lat: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
